---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Java
  apt:
    name: openjdk-17-jdk
    state: present
  when: ansible_os_family == "Debian"

- name: Install Java
  yum:
    name: java-17-openjdk
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Maven
  apt:
    name: maven
    state: present
  when: ansible_os_family == "Debian"

- name: Install Maven
  yum:
    name: maven
    state: present
  when: ansible_os_family == "RedHat"

- name: Create application directory
  file:
    path: /opt/app
    state: directory
    owner: deployuser
    group: deployuser

- name: Copy Java application
  copy:
    src: /mnt/c/Users/Mohammed Khazzani/path/to/your/application.jar # Fixed
    dest: /opt/app/application.jar
    owner: deployuser
    group: deployuser

- name: Create systemd service file
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Enable and start systemd service
  systemd:
    name: app.service
    state: started
    enabled: true

- name: Open firewall port if needed
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
